### PR TITLE
Fix embed param parsing, remove "responsive"

### LINKED ISSUE #885: Embed options aren't being encoded in the URL
From our friends at Unredacted:

> Then, once toggling the various options, they don't seem to make any difference - eg I tried 1 and 0 values for sidebar, title, pdf etc and they didn't change any elements. Width also.

### PR DESCRIPTION
**Pull request by eyeseast**
Stricter parsing of embeds into real types, so `"0"` becomes `0` and `"false"` becomes `false`.

Removed the `responsive` option because everything is responsive now.

Closes #885

### CODE REVIEW

File: src/lib/components/embeds/DocumentEmbed.svelte [hunk 1]
```diff
@@ -30,6 +30,8 @@
     ? document.organization.name
     : undefined;
   $: contributedBy = settings.onlyshoworg ? org : `${user} (${org})`;
+
+  $: console.log(settings);
```
Comment (allanlasser) [inline src/lib/components/embeds/DocumentEmbed.svelte:34]: Remove before shipping
```suggestion
```

**Review by allanlasser — APPROVED** [review]
