### PR TITLE
Maybe handle redirects manually"

### LINKED ISSUE #321: Text view broken in private documents
Turns out we need a two-step request and can't do a normal redirect on private documents.

### PR DESCRIPTION
**Pull request by eyeseast**
Partially undoes #319 but in a way that redirects based on a location header, instead of hostname. 

Example document, private to MuckRock: https://deploy-preview-322.muckcloud.com/documents/20006188-change-assessment_w_mjw-letter

Closes #321

### CODE REVIEW

File: src/api/session.js [hunk 1]
```diff
@@ -84,9 +84,20 @@ export class SessionCache {
...
 session.getStatic = async function getStatic(url) {
-  if (sessionCache.has(url)) return sessionCache.lookup(url);
+  if (sessionCache.has(url)) {
+    return sessionCache.lookup(url);
+  }
+
+  let result = await session.get(url).then((r) => r.data);
+  let redirect = result.location;
+
+  // text requests return a 200 but have a location header
```
Comment (mitchelljkotler) [inline src/api/session.js:94]: Just to prevent confusion in the future - they do not have a location header like a 302, they return JSON with a location ie:
`{"location": "https://www.example.com/go_here/"}`
I believe `r.data` is fetching the parsed JSON, and `result.location` is accessing the proper property (as exhibited by it working on the deploy preview), but the comment here should be updated

**Review by mitchelljkotler — CHANGES_REQUESTED** [review]

File: src/api/session.js (hunk 1 above)
Comment (eyeseast) [reply src/api/session.js]: Updated

**Review by mitchelljkotler — APPROVED** [review]
