### PR TITLE
Use getApiResponse on infinite scrolls, too

### LINKED ISSUE #829: Handle infinite scroll load failures
Sometimes `fetch` fails (because of API issues) in our infinite scroll handling. This doesn't break the page, but we should deal with it.

https://muckrock.sentry.io/issues/6062280415/events/1e1f276d2c334b308326c44735bed7ea/

### PR DESCRIPTION
**Pull request by eyeseast**
Closes #829 

This aligns our infinite scroll handling with other places we hit the API and lets us show an error message when something fails.

### CODE REVIEW

File: src/lib/components/addons/History.svelte [hunk 1]
```diff
@@ -3,41 +3,46 @@
   import type { Run } from "$lib/api/types";
 
   import { _ } from "svelte-i18n";
-  import { History16, History24, Hourglass24 } from "svelte-octicons";
+  import { Alert16, History16, History24, Hourglass24 } from "svelte-octicons";
```
Comment (allanlasser) [inline src/lib/components/addons/History.svelte:6]:
```suggestion
  import { Alert24, History16, History24, Hourglass24 } from "svelte-octicons";
```

File: src/lib/components/addons/History.svelte [hunk 2]
```diff
@@ -50,6 +55,10 @@
 
   {#if loading}
     <Empty icon={Hourglass24}>Loading past runs…</Empty>
+  {:else if error}
+    <Empty icon={Alert16}>
```
Comment (allanlasser) [inline src/lib/components/addons/History.svelte:59]: Larger icon variants work better in this slot:

```suggestion
    <Empty icon={Alert24}>
```

File: src/lib/components/addons/Scheduled.svelte [hunk 3]
```diff
@@ -2,39 +2,45 @@
   import type { Maybe, Nullable, Page, Event } from "$lib/api/types";
 
   import { _ } from "svelte-i18n";
-  import { Clock16, Hourglass24 } from "svelte-octicons";
+  import { Alert16, Clock16, Hourglass24 } from "svelte-octicons";
```
Comment (allanlasser) [inline src/lib/components/addons/Scheduled.svelte:5]:
```suggestion
  import { Alert24, Clock16, Hourglass24 } from "svelte-octicons";
```

File: src/lib/components/addons/Scheduled.svelte [hunk 4]
```diff
@@ -47,6 +53,10 @@
 
   {#if loading}
     <Empty icon={Hourglass24}>{$_("common.loading")}</Empty>
+  {:else if error}
+    <Empty icon={Alert16}>
```
Comment (allanlasser) [inline src/lib/components/addons/Scheduled.svelte:57]:
```suggestion
    <Empty icon={Alert24}>
```

File: src/lib/components/documents/ResultsList.svelte [hunk 5]
```diff
@@ -145,12 +149,17 @@
...
         {:else}
-          Load more
+          {$_("documents.more")}
         {/if}
       </Button>
     {/if}
+
+    {#if error}
+      <p class="error">{error}</p>
+      <p class="error">{$_("documents.retry")}</p>
```
Comment (allanlasser) [inline src/lib/components/documents/ResultsList.svelte:161]: "Retry" should give the user some kind of actionable step. Since we have the load function available, this could be a button to call it again for the URL. Instead of "Please try again," the UI string could just be "Try Again"

File: src/lib/components/documents/ResultsList.svelte [hunk 6]
```diff
@@ -177,6 +186,12 @@
...
   .end {
     display: flex;
-    justify-content: center;
+    flex-direction: column;
+    align-items: center;
+    gap: 0.5rem;
+  }
+
+  .error {
+    color: var(--error, red);
```
Comment (allanlasser) [inline src/lib/components/documents/ResultsList.svelte:195]: Since we're showing text stacked in a centered container, let's center it, too:

```suggestion
    text-align: center;
    color: var(--error, red);
```

**Review by allanlasser — CHANGES_REQUESTED** [review]
