### PR TITLE
Try fetching project first, then retry with old pattern

### LINKED ISSUE #1053: Projects with slugs ending in a number match wrong
The redirect for old project embed URLs is over-matching.

### PR DESCRIPTION
**Pull request by eyeseast**
Maybe fixes #1053 

This potentially makes an extra fetch, but only if the first try fails.

### CODE REVIEW

File: src/routes/embed/projects/[project_id]-[slug]/+page.ts [hunk 1]
```diff
@@ -11,28 +11,31 @@ const OLD_PATTERN = /(\D+)-(\d+)/;
...
-    return error(404, "Project not found");
-  }
-
-  const project = await get(+project_id, fetch);
-  const documents = search(`+project:${project_id}`, undefined, fetch);
+  let project = await get(+project_id, fetch);
 
+  // old project embeds used a pattern of <slug>-<id>
+  // so we want to give 404s a chance to try again
   if (project.error) {
```
Comment (allanlasser) [inline src/routes/embed/projects/[project_id]-[slug]/+page.ts:19]: Can we branch on `project.error.status === 404` so we're not making extra requests for 403, 500, etc?

**Review by allanlasser — CHANGES_REQUESTED** [review]
I like this approach, rather than trying to go deeper down the regex route. I think the retry condition could be make more specific, otherwise looks good.

File: src/routes/embed/projects/[project_id]-[slug]/+page.ts (hunk 1 above)
Comment (eyeseast) [reply src/routes/embed/projects/[project_id]-[slug]/+page.ts:19]: Good call. Done.

**Review by allanlasser — APPROVED** [review]
